import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Slider from '../component/Slider'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next js Owl Carousel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
     <h1>Owl Carousel by react-owl-carousel </h1>
     <Slider />
      </main>


    </div>
  )
}
